// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTIGK9NTnjTbuagXSrVyfHjO0G_Y67XTQ',
    appId: '1:520713336303:web:64ee532188a00a1baa321a',
    messagingSenderId: '520713336303',
    projectId: 'mapapp-fdfdc',
    authDomain: 'mapapp-fdfdc.firebaseapp.com',
    storageBucket: 'mapapp-fdfdc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs0PLhqHl8vkMfs8e6HZnDOHeKGXTfuA4',
    appId: '1:520713336303:android:b0972beb5ded34d8aa321a',
    messagingSenderId: '520713336303',
    projectId: 'mapapp-fdfdc',
    storageBucket: 'mapapp-fdfdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD3YGkIZ2VQIIKaI-0j1f3Tzd2UzVY3vE',
    appId: '1:520713336303:ios:79dbbe2b96a33b15aa321a',
    messagingSenderId: '520713336303',
    projectId: 'mapapp-fdfdc',
    storageBucket: 'mapapp-fdfdc.firebasestorage.app',
    iosBundleId: 'com.example.mapflutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD3YGkIZ2VQIIKaI-0j1f3Tzd2UzVY3vE',
    appId: '1:520713336303:ios:79dbbe2b96a33b15aa321a',
    messagingSenderId: '520713336303',
    projectId: 'mapapp-fdfdc',
    storageBucket: 'mapapp-fdfdc.firebasestorage.app',
    iosBundleId: 'com.example.mapflutterapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTIGK9NTnjTbuagXSrVyfHjO0G_Y67XTQ',
    appId: '1:520713336303:web:c7c071ebd97e1b5baa321a',
    messagingSenderId: '520713336303',
    projectId: 'mapapp-fdfdc',
    authDomain: 'mapapp-fdfdc.firebaseapp.com',
    storageBucket: 'mapapp-fdfdc.firebasestorage.app',
  );
}
